import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bollouf
 */

public class addgrade extends javax.swing.JFrame {

    /**
     * Creates new form addgrade
     */
    public addgrade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentidlabel = new javax.swing.JLabel();
        examIdLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        studentIdtext = new javax.swing.JTextField();
        examIdText = new javax.swing.JTextField();
        gradeText = new javax.swing.JTextField();
        addgradeButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Grades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 3, 24))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        studentidlabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        studentidlabel.setText("Student Id");

        examIdLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        examIdLabel.setText("Exam ID");

        gradeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gradeLabel.setText("Grade");

        studentIdtext.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        examIdText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        gradeText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        addgradeButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addgradeButton.setText("Add Grade");
        addgradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addgradeButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(examIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addgradeButton)
                        .addGap(23, 23, 23)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentIdtext)
                    .addComponent(examIdText)
                    .addComponent(gradeText)
                    .addComponent(clearButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentidlabel)
                    .addComponent(studentIdtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(examIdLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addgradeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton)))
        );

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // exit the progrm
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // clear all entry fields
        examIdText.setText("");
        studentIdtext.setText("");
        gradeText.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void dealWithMissing( boolean studentFound, boolean examFound, int studentID, int examID, int grade) {
        //  I will treat the case of missing info here
        String errorMsg = null;
        if (studentFound && !examFound) {
        // The student is found but not the exam 
            errorMsg = "Exam " + examID + " not found";
            System.out.println("Exam Missing");
            }
            else if (!studentFound && examFound) {
            // The student is not found but the exam is found 
                errorMsg = "Student " + studentID + " not found";
                System.out.println("Student Missing");
                }
                else {
                    // Both The student and the exam are not found 
                    errorMsg = "both Student " + studentID + " and exam " + examID + " not found";
                    System.out.println("Exam and student Missing");
                }
        
        // this means there was something missing therefore I will write the missing file
        System.out.println(" something missing " + studentFound + " " + examFound);
        File file = new File("missingRecords.txt");
        try {
            PrintWriter writer = new PrintWriter(file);
            writer.println("--- BEGIN RECORD ---");
            writer.println("Student Id: " + studentID);
            writer.println("Exam Id: " + examID);
            writer.println("Grade: " + grade);
            writer.println(errorMsg);
            writer.println("--- END RECORD ---");
            writer.close();
            System.out.println(" error missing File printed successfully");
            JOptionPane.showMessageDialog(null, "There was a missing ID.. see file",null, 2);   
        }
        catch(Exception ex){
            System.out.println("There was a file error " + ex.getMessage());   
        }
    }



    
    private void addgradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addgradeButtonActionPerformed
        // I need to establish a DB connection 
        
        Connection conn = null;
        
        // declaring a few variables to use later
        
        PreparedStatement statement = null;
        ResultSet res1 = null;
        ResultSet res2 = null;
        boolean studentFound = false;
        boolean examFound = false;
        boolean missing = true;
        
          
        // Get all three entries from user
        
        int studentID = Integer.parseInt(studentIdtext.getText());
        int examID = Integer.parseInt(examIdText.getText());
        int grade = Integer.parseInt(gradeText.getText());
        // preparing my queries and statements
        String queryStudent = "SELECT * FROM student WHERE studentID = " +studentID+";";
        String queryExam = "SELECT * FROM exam WHERE examiD = " +examID+ ";";
        String insertGrade = "INSERT INTO grades (studentID, examID, Grade) values("
                +studentID+","
                +examID+","
                +grade
                +")";
        //  I will now try to access the database
        
        try {
            conn = ConnectionTest.getConnection();
            Statement stm = conn.createStatement();
            System.out.println("DB Connection successful");
            // Need to read the student table
            
            res1 = stm.executeQuery(queryStudent);
            System.out.println("execute query successful");
            // check if I found the student
            while (res1.next()){
                studentFound = true;
                System.out.println("student found " + studentFound);
            }
            // Need to read the exam table
            
            res2 = stm.executeQuery(queryExam);
            System.out.println("execute query exam successful");
            // check if I found the exam
            while (res2.next()){
                examFound = true;
                System.out.println("exam found " + examFound);
            }
            // now if I found both, I can add the grade
            if (studentFound && examFound) {
                stm.execute(insertGrade);
                missing = false;
                JOptionPane.showMessageDialog(null, "Sucess", null, 1);
            }
            else {
                missing = true;
                dealWithMissing (studentFound, examFound, studentID, examID, grade);
            }
            System.out.println("value of Missing " + missing);
            conn.close();
            System.exit(1);
            
        }
        catch (Exception e) {
            System.err.println("There was a problem with database " + e.getMessage());
        } 
        finally {
            ConnectionTest.closeConnection(conn);

        }

    }//GEN-LAST:event_addgradeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addgrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addgrade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addgradeButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel examIdLabel;
    private javax.swing.JTextField examIdText;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JTextField gradeText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField studentIdtext;
    private javax.swing.JLabel studentidlabel;
    // End of variables declaration//GEN-END:variables
}
